site_name: HungryHub
theme: 
  name: material

nav:
  - Home: index.md
  - Guia de Contribuição: GuiaContribuicao.md
  - Código de Conduta: CodigoConduta.md
  - Template: Template.md
  - 1. Base:
    - Desenho de Software (Base): Base/1.Base.md
    - 1.1. Design Sprint:
      - Módulo Design Sprint: Base/DesignSprint/1.1.DesignSprint.md 
      - Mapa Mental: Base/DesignSprint/MapaMental.md
      - Rich Picture: Base/DesignSprint/RichPictures.md
      - Storyboarding: Base/DesignSprint/Storyboarding.md
      - Protótipo: Base/DesignSprint/Prototipo.md
    - 1.2. Artefato Generalista:
      - Módulo Artefato Generalista: Base/ArtefatoGeneralista/1.2.ArtefatoGeneralista.md
      - 5W2H: Base/ArtefatoGeneralista/5W2H.md
      - Causa e Efeito: Base/ArtefatoGeneralista/CausaEfeito.md
      - Rich Picture: Base/ArtefatoGeneralista/RichPicture.md
    - 1.3. Modelagem BPMN: Base/ModelagemBPMN/1.3.ModelagemBPMN.md
    - 1.4. Artefatos Extras:
      - Baseline: Base/DesignSprint/Requisitos/Baseline.md
      - Brainstorming: Base/DesignSprint/Requisitos/Brainstorming.md
      - Introspecção: Base/DesignSprint/Requisitos/Introspeccao.md
  # - Modelagem:
  # - Padrões de Projeto:
  # - Documento de Arquitetura de Software: