site_name: HungryHub
theme: 
  name: material

nav:
  - Home: index.md
  - Guia de Contribuição: GuiaContribuicao.md
  - Código de Conduta: CodigoConduta.md
  - Template: Template.md
  - 1. Base:
    - Desenho de Software (Base): Base/1.Base.md
    - 1.1. Design Sprint:
      - Módulo Design Sprint: Base/DesignSprint/1.1.DesignSprint.md 
      - Mapa Mental: Base/DesignSprint/MapaMental.md
      - Rich Picture: Base/DesignSprint/RichPictures.md
      - Storyboarding: Base/DesignSprint/Storyboarding.md
      - Protótipo: Base/DesignSprint/Prototipo.md
    - 1.2. Artefato Generalista:
      - Módulo Artefato Generalista: Base/ArtefatoGeneralista/1.2.ArtefatoGeneralista.md
      - 5W2H: Base/ArtefatoGeneralista/5W2H.md
      - Causa e Efeito: Base/ArtefatoGeneralista/CausaEfeito.md
      - Rich Picture: Base/ArtefatoGeneralista/RichPicture.md
    - 1.3. Modelagem BPMN: Base/ModelagemBPMN/1.3.ModelagemBPMN.md
    - 1.4. Artefatos Extras:
      - Baseline: Base/DesignSprint/Requisitos/Baseline.md
      - Brainstorming: Base/DesignSprint/Requisitos/Brainstorming.md
      - Introspecção: Base/DesignSprint/Requisitos/Introspeccao.md
  - 2. Modelagem:
    - Desenho de Software (Modelagem): Modelagem/2.Modelagem.md
    - 2.1. Modelagem Estática:
      - Módulo Modelagem Estática: Modelagem/ModelagemEstatica/2.1.ModelagemEstatica.md
      - Diagrama de Classes: Modelagem/ModelagemEstatica/DiagramaClasses.md
      - Diagrama de Componentes: Modelagem/ModelagemEstatica/DiagramaComponentes.md
    - 2.2. Modelagem Dinâmica:
      - Módulo Modelagem Dinâmica: Modelagem/ModelagemDinamica/2.2.ModelagemDinamica.md
      - Diagrama de Sequência: Modelagem/ModelagemDinamica/DiagramaSequencia.md
      - Diagrama de Estados: Modelagem/ModelagemDinamica/DiagramaDeEstados.md
      - Diagrama de Atividades: Modelagem/ModelagemDinamica/Diagrama_de_atividades.md
    - 2.3. Modelagem Organizacional:
      - Módulo Modelagem Organizacional: Modelagem/ModelagemOrganizacional/2.3.ModelagemOrganizacionalCasosDeUso.md
      - Casos de Uso Geral: Modelagem/ModelagemOrganizacional/DiagramaCasosDeUsoGeral.md
      - Casos de Uso Cliente: Modelagem/ModelagemOrganizacional/CasosDeUsoCliente.md
      - Casos de Uso Loja: Modelagem/ModelagemOrganizacional/DiagramaCasosDeUsoLoja.md
      - Casos de Uso Entregador: Modelagem/ModelagemOrganizacional/CasosDeUsoEntregador.md
    - 2.4 Artefatos Extras:
      - Baseline: Modelagem/Extra/Baseline.md
      - Priorização: Modelagem/Extra/Priorizacao/Priorizacao.md
      - Léxicos: Modelagem/Extra/Lexicos.md
      - Especificação Suplementar: Modelagem/Extra/especificacao-suplementar.md
      - Cenários:
        - Introdução: Modelagem/Extra/Cenarios/introducao.md
        - Cenários Elicitados: Modelagem/Extra/Cenarios/cenarios.md
      - Elicitação:
        - Elicitação: Modelagem/Extra/Elicitacao/Elicitacao.md
        - Entrevistas: Modelagem/Extra/Elicitacao/Entrevistas.md
      - Modelagem Ágil:
        - Backlog: Modelagem/Extra/ModelagemAgil/Backlog.md
        - Priorização das USs: Modelagem/Extra/ModelagemAgil/Priorizacaous.md
      - Validação do Protótipo: Modelagem/Extra/ValidacaoPrototipo.md
      - Diagrama Modelo Relacional: Modelagem/Extra/DiagramaModeloRelacional.md    
  - 3. Padrões de Projeto:
    - Desenho de Software (Padrões de Projeto): PadroesDeProjeto/3.PadroesDeProjeto.md
    - 3.1 GoFs Criacionais:
      - Módulo Padrões GoFs Criacionais: PadroesDeProjeto/GoFsCriacionais/3.1.GoFsCriacionais.md
      - Abstract Factory: PadroesDeProjeto/GoFsCriacionais/AbstractFactory.md
      - Builder: PadroesDeProjeto/GoFsCriacionais/Builder.md
      - Factory Method: PadroesDeProjeto/GoFsCriacionais/FactoryMethod.md
      - Prototype: PadroesDeProjeto/GoFsCriacionais/Prototype.md
      - Singleton: PadroesDeProjeto/GoFsCriacionais/Singleton.md
    - 3.2 GoFs Estruturais:
      - Módulo Padrões GoFs Estruturais: PadroesDeProjeto/GoFsEstruturais/3.2.GoFsEstruturais.md
      - Adapter: PadroesDeProjeto/GoFsEstruturais/Adapter.md
      - Composite: PadroesDeProjeto/GoFsEstruturais/Composite.md
      - Decorator: PadroesDeProjeto/GoFsEstruturais/Decorator.md
      - Facade: PadroesDeProjeto/GoFsEstruturais/Facade.md
    - 3.3 GoFs Comportamentais:
      - Módulo Padrões GoFs Comportamentais: PadroesDeProjeto/GoFsComportamentais/3.3.GoFsComportamentais.md
      - Command: PadroesDeProjeto/GoFsComportamentais/Command.md
      - Iterator: PadroesDeProjeto/GoFsComportamentais/Iterator.md
      - Observer: PadroesDeProjeto/GoFsComportamentais/Observer.md
      - State: PadroesDeProjeto/GoFsComportamentais/State.md
      - Strategy: PadroesDeProjeto/GoFsComportamentais/Strategy.md
      - Template Method: PadroesDeProjeto/GoFsComportamentais/TemplateMethod.md
    - 3.4 Artefatos Extras:
      - Elos de Casos de Uso: PadroesDeProjeto/Extra/ElosCasos.md
      - Elos de Cenários: PadroesDeProjeto/Extra/ElosCenarios.md
      - Elos de Histórias de Usuário: PadroesDeProjeto/Extra/ElosHistorias.md
  # - Documento de Arquitetura de Software: